services:

  backend:
    build: ./Backend
    env_file:
      - ./Backend/.env
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
    depends_on:
      - backend